apiVersion: apps/v1
# Wraps the application (from image on line 19) into a pod - this lets the control plane communicate to the container.
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          # docker image from tutorial video
          image: amigoscode/kubernetes:springboot-react-fullstack-v1
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

# Creates a service - allows to amke the deployment available to the internal network (ie the cluster)
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80
      # target port is the port on which the service will send requests to! This is the port that our pod, "myapp" will be listening on!
      targetPort: 8080
